baseURL = 'https://example.org/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'ふぁしぶろぐ'

[params]
  author = 'kouphasi'
  description = 'kouphasiの日々の学びを殴り書きしていくブログです'
  disableSpecial1stPost = true

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
